version: '3.2'

services:
  db:
    image: mysql:5.7
    container_name: cicd-mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password-secret
      MYSQL_DATABASE: sonar
      MYSQL_USER: sonar
      MYSQL_PASSWORD: sonar
    volumes:
      - type: bind
        source: ${CICD_HOME}/data/mysql
        target: /var/lib/mysql
      - type: bind
        source: ${CICD_HOME}/config/mysql
        target: /etc/mysql/conf.d
    ports:
      - "3306:3306"
  sonar:
    image: sonarqube
    container_name: cicd-sonar
    restart: always
    ports:
      - "9000:9000"
    environment:
      - "sonar.jdbc.username=sonar"
      - "sonar.jdbc.password=sonar"
      - "sonar.jdbc.url=jdbc:mysql://localhost:3306/sonar"
    volumes:
      - type: bind
        source: ${CICD_HOME}/sonar/extensions
        target: /opt/sonarqube/extensions
  jenkins:
    image: jenkinsci/blueocean
    container_name: cicd-jenkins
    restart: always
    ports:
      - "8080:8080"
    environment:
      JAVA_OPTS: "-Xmx1024m"
      JENKINS_OPTS: "--prefix=/jenkins"
    volumes:
      - type: bind
        source: ${CICD_HOME}/data/jenkins
        target: /var
      - type: bind
        source: /var/run/docker.sock
        target: /var/run/docker.sock
  nexus:
    image: sonatype/nexus3
    container_name: cicd-nexus3
    restart: always
    ports:
      - "8081:8081"
    volumes:
      - type: bind
        source: ${CICD_HOME}/data/nexus3
        target: /nexus-data