pipeline {
    agent any
    tools {
      maven 'maven 3.6.1'
      jdk 'jdk8'
    }

    stages {

     stage ('Initialize'){
       steps {
           sh '''
             echo "path=${path}"
             echo "M2_HOME=${M2_HOME}"
             echo | mvn -version
             echo | java -version
             echo | git --version
           '''
       }
     }

     stage ('SCM'){
       steps {
          checkout scm
          sh "ls -lat"
       }
     }

     stage ('build'){
       steps {
         sh '''
            mvn -f cicd/cicd-mule/pom.xml -s cicd/settings.xml clean package -DskipTests
         '''
       }
     }


      stage ('MUnit'){
            steps {
              sh '''
                 mvn -f cicd/cicd-mule/pom.xml -s cicd/settings.xml test
              '''
            }
      }


      stage ('Deploy to Nexus Repository'){
            steps {
               sh '''
                mvn -f cicd/cicd-mule/pom.xml -s cicd/settings.xml deploy -DaltSnapshotDeploymentRepository=snapshots::default::http://cicd-nexus3:8081/repository/maven-snapshots/
               '''
            }
      }






    }

}