pipeline {
    agent any
    tools {
      maven 'maven 3.6.1'
      jdk 'jdk8'
    }

    stages {

     stage ('Initialize'){
       steps {
           sh '''
             echo "path=${path}"
             echo "M2_HOME=${M2_HOME}"
             echo | mvn -version
             echo | java -version
             echo | git --version
           '''
       }
     }

     stage ('SCM'){
       steps {
          checkout scm
          sh "ls -lat"
       }
     }

     stage ('build'){
       steps {
         sh '''
            mvn -f cicd/cicd-mule/pom.xml clean install -X
         '''
       }
     }


    }

}